FORMAT: 1A
HOST: https://hostname/ikea/md/shipping

# IKEA Shipping APIs

IKEA Shipping APIs provide details on shipping of IKEA products from manufacturing and distribution sectors directly.
This include IKEA compliance information of shipment, order volumes allowed as per consumer organisation, cost estimates.

## Who is this for!

+ Retailers/partners who wants to buy products from manufacturing unit directly

## Authentication

IKEA Shipping APIs not allowed for developer/public use. To be used only by registered consumers.
Requests must always include `apiKey` as one of the parameters for authentication.

## Compliance on import and export [/isCompliant{?apiKey,format}]

A shipment is allowed only if it is IKEA import/export compliant.
You can check if your shipment is IKEA compliant using this action.
This action takes JSON payload as part of the request.
Response shall be IKEA compliance data and if compliant or not.

## Is shipment IKEA Compliant? [POST]

+ Parameters

    + format: `JSON` (string, optional)
        + Default: `JSON`
    + apiKey: `<api-key>` (string, required) - Your unique api key
    
+ Request (application/json)

        {
            "orgName": "Capgemini Retailers",
            "orgId" : "aexas0001",
            "address" : {
                "street" : "Divyasree, Whitefield",
                "city" : "Bangalore",
                "country" : "India",
                "postal code": "560037"
            },
            "shipments": [
                {
                    "weight" : {"value": 100, "unit": "Kg"},
                    "size" : {"length" : 200, "width": 200, "height" : 100 , "unit": "inches"},
                    "shippingDuration" : {"value": 30, "unit": "days"},
                    "itemCategory" : "fragile",
                    "transportMode" : "air"
                }
            ]
        }
        
+ Response 200 (application/json)

        {
            "compliance data" : "IKEA compliance message",
            "compliance" : "yes/no"
        }

+ Response 401 (application/json)
    
        {
            "error": "Invalid apiKey"
        }

+ Response 402 (application/json)

        {
            "error" : "Invalid request"
        }

## Order volume limitations [/isShipmentAllowed{?apiKey,format}]

IKEA has some limitations on order volumes based on consumer organisation.
You can use this action to check if volume of your shipment is allowed.
This action takes JSON payload as part of the request.
Response shall be shipment allowed or not.

## Is shipment volume allowed? [POST]

+ Parameters

    + format: `JSON` (string, optional)
        + Default: `JSON`
    + apiKey: `<api-key>` (string, required) - Your unique api key
    
+ Request (application/json)

        {
            "orgName": "Capgemini Retailers",
            "orgId" : "aexas0001",
            "address" : {
                "street" : "Divyasree, Whitefield",
                "city" : "Bangalore",
                "country" : "India",
                "postal code": "560037"
            },
            "shipments": [
                {
                    "weight" : {"value": 100, "unit": "tons"},
                    "size" : {"length" : 200, "width": 200, "height" : 100 , "unit": "inches"},
                    "shippingDuration" : {"value": 30, "unit": "days"},
                    "itemCategory" : "fragile",
                    "transportMode" : "air"
                }
            ]
        }
        
+ Response 200 (application/json)

        {
            "allowed" : "yes/no"
        }

+ Response 401 (application/json)
    
        {
            "error": "Invalid apiKey"
        }

+ Response 402 (application/json)

        {
            "error" : "Invalid request"
        }

## Shipment cost estimate [/getCostEstimate{?apiKey,format}]

You can use this action to get the cost estimate of your shipment
This action takes JSON payload as part of the request.
Response shall be cost estimate.

## get cost estimate [POST]

+ Parameters

    + format: `JSON` (string, optional)
        + Default: `JSON`
    + apiKey: `<api-key>` (string, required) - Your unique api key
    
+ Request (application/json)

        {
            "orgName": "Capgemini Retailers",
            "orgId" : "aexas0001",
            "address" : {
                "street" : "Divyasree, Whitefield",
                "city" : "Bangalore",
                "country" : "India",
                "postal code": "560037"
            },
            "shipments": [
                {
                    "weight" : {"value": 100, "unit": "tons"},
                    "size" : {"length" : 200, "width": 200, "height" : 100 , "unit": "inches"},
                    "shippingDuration" : {"value": 30, "unit": "days"},
                    "itemCategory" : "fragile",,
                    "transportMode" : "air",
                    "priceUnit" : "INR"
                }
            ]
        }
        
+ Response 200 (application/json)

        {
            "costEstimate" : 234543,
            "unit" : "INR"
        }

+ Response 401 (application/json)
    
        {
            "error": "Invalid apiKey"
        }

+ Response 402 (application/json)

        {
            "error" : "Invalid request"
        }

# Group General
- Length unit by default in `inches`. You may use any of (`cm`, `inch`, `m`, `km`, `mile`) 
- Width unit by default in `inches`. You may use any of (`cm`, `inch`, `m`, `km`, `mile`) 
- Height unit by default in `inches`. You may use any of (`cm`, `inch`, `m`, `km`, `mile`) 
- Weight unit by default in kilograms `kg`. You may append any of (`kg`, `ton`, `lb`, `oz`)
- ItemCategory allowed values are `fragile`, `non-fragile`
- TransportMode allowed values are `air`, `road`, `water`